version: '3'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: Api/Dockerfile
    depends_on:
      - sql.data

  sql.data:
    image: microsoft/mssql-server-linux:2017-latest