version: '3'

services:
  api:
    environment:
      - ConnectionString=${Db:-Server=sql.data;Database=master;User Id=sa;Password=Pass@word}
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"

  sql.data:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
